import React, { useState, useEffect } from "react";
import {
  SafeAreaView,
  View,
  FlatList,
  StyleSheet,
  Text,
  StatusBar,
  TextInput,
} from "react-native";

const DATA = [
  {
    _id: "61d1752e339d0c456d8bf299",
    Address: "Alexandria 164 Kingsclear Road",
    Location: "West side, between Henderson Lane and Henderson Road",
    ParkingSpace: "1 parallel parking space, 2.2m wide by 4m long",
    StreetView: "https://goo.gl/s3eoLu",
  },
  {
    _id: "61d1752e339d0c456d8bf29a",
    Address: "Alexandria 142 Henderson Road",
    Location: "South side, between Mitchell Road and Alexander Street",
    ParkingSpace: "1 parallel parking space, 2.7m wide by 6.6m long",
    StreetView: "https://goo.gl/YoPp69",
  },
  {
    _id: "61d1752e339d0c456d8bf29b",
    Address: "Annandale rear of Webber's Carpet Warehouse Nelson Street",
    Location: "East side, corner of Nelson Street and Chapman Road",
    ParkingSpace: "290-degree parking spaces, 3.3m wide by 5.4m long",
    StreetView: "https://goo.gl/acv2iD",
  },
  {
    _id: "61d1752e339d0c456d8bf29c",
    Address: "Annandale 6 Chapman Road",
    Location: "East side, Chapman Road cul de sac near the lightrail bridge",
    ParkingSpace: "190-degree parking space, 4.1m wide by 5.4m long",
    StreetView: "https://goo.gl/CDdWFs",
  },
  {
    _id: "61d1752e339d0c456d8bf29d",
    Address: "Annandale 2-2A Chapman Road",
    Location: "East side, opposite Federal Park Playground",
    ParkingSpace: "290-degree parking spaces, 3.5m wide by 4.6m long",
    StreetView: "https://goo.gl/nmRLhB",
  },
  {
    _id: "61d1752e339d0c456d8bf29e",
    Address: "Beaconsfield Reserve Street",
    Location: "South side, between Botany Road and Beaconsfield Lane",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 7.8m long",
    StreetView: "https://goo.gl/X9Gm1z",
  },
  {
    _id: "61d1752e339d0c456d8bf29f",
    Address: "Camperdown 100 Mallett Street",
    Location: "East side, between Hampshire Lane and Fowler Street",
    ParkingSpace: "2 parallel parking spaces, 3.2m wide by 6.8m long",
    StreetView: "https://goo.gl/maps/mEMpdmjoN8JMatCm8",
  },
  {
    _id: "61d1752e339d0c456d8bf2a0",
    Address: "Camperdown 54-60 Briggs Street",
    Location: "North side, between Church Street and Missenden Road",
    ParkingSpace: "2 parallel parking spaces, 3.2m wide by 6m long",
    StreetView: "https://goo.gl/vcdJqM",
  },
  {
    _id: "61d1752e339d0c456d8bf2a1",
    Address: "Camperdown 46 Dunblane Street",
    Location: "North side, between Missenden Road and Church Street",
    ParkingSpace: "2 parallel parking spaces, 3.2m wide by 4.8m long",
    StreetView: "https://goo.gl/tEM9Ed",
  },
  {
    _id: "61d1752e339d0c456d8bf2a2",
    Address: "Camperdown 92 Church Street",
    Location: "East side, between Dunblane Street and Lucas Street",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 8.5m long",
    Information: "30 minute parking",
    StreetView: "https://goo.gl/grMhhR",
  },
  {
    _id: "61d1752e339d0c456d8bf2a3",
    Address: "Camperdown 4 Lambert Street",
    Location: "North side, between Lyons Road and Layton Street",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 5.7m long",
    StreetView: "https://goo.gl/vYdALg",
  },
  {
    _id: "61d1752e339d0c456d8bf2a4",
    Address: "Centennial Park 55 Moore Park Road",
    Location: "South side, between Cook Road and Poate Road",
    ParkingSpace: "1 parallel parking space, 2.6m wide by 7.4m long",
    StreetView: "https://goo.gl/7JLHju",
  },
  {
    _id: "61d1752e339d0c456d8bf2a5",
    Address: "Centennial Park 60 Cook Road",
    Location: "West side, between Furber Road and Furber Lane",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 4.4m long",
    StreetView: "https://goo.gl/qLPyjA",
  },
  {
    _id: "61d1752e339d0c456d8bf2a6",
    Address: "Centennial Park 41 Robertson Road",
    Location: "South side, between Dibbs Street and Oxley Lane",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 5.4m long",
    StreetView: "https://goo.gl/WSMvtH",
  },
  {
    _id: "61d1752e339d0c456d8bf2a7",
    Address: "Chippendale Myrtle Street",
    Location: "North side, between City Road and Paints Lane",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 6.8m long",
    StreetView: "https://goo.gl/ndcijv",
  },
  {
    _id: "61d1752e339d0c456d8bf2a8",
    Address: "Chippendale 71 Regent Street",
    Location: "West side, between Kensington Street and Outram Street",
    ParkingSpace: "1 parallel parking space, 3.5m wide by 6.2m long",
    StreetView: "https://goo.gl/maps/QGy3VrKWCaXZKPzp7",
  },
  {
    _id: "61d1752e339d0c456d8bf2a9",
    Address: "Darlinghurst 341 Bourke Street",
    Location: "West side, between Foley Street and Burton Street",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 8.1m long",
    StreetView: "https://goo.gl/btaKxv",
  },
  {
    _id: "61d1752e339d0c456d8bf2aa",
    Address: "Darlinghurst 407 South Dowling Street",
    Location: "West side, between Flinders Street and Hannam Street",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 6m long",
    StreetView: "https://goo.gl/NsPQho",
  },
  {
    _id: "61d1752e339d0c456d8bf2ab",
    Address: "Darlinghurst 301 Forbes Street",
    Location: "West side, between Foley Street and Burton Street",
    ParkingSpace: "760-degree parking spaces, 3.2m wide by 4.8m long",
    Information:
      "60 degree angle parking front to kerb. Vehicles under 6 metres only",
    StreetView: "https://goo.gl/1iio1X",
  },
  {
    _id: "61d1752e339d0c456d8bf2ac",
    Address: "Darlinghurst 77 Surrey Street",
    Location: "North side, between Caldwell Street and Surry Lane",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 5.5m long",
    StreetView: "https://goo.gl/dmyiAq",
  },
  {
    _id: "61d1752e339d0c456d8bf2ad",
    Address: "Darlinghurst Caldwell Street",
    Location: "West side, between Surry Street and Nimrod Street",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 4.2m long",
    StreetView: "https://goo.gl/ircYPm",
  },
  {
    _id: "61d1752e339d0c456d8bf2ae",
    Address: "Darlinghurst 43 Boundary Street",
    Location: "North side, between Glenview Lane and Glenview Street",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 7m long",
    StreetView: "https://goo.gl/v1aJtH",
  },
  {
    _id: "61d1752e339d0c456d8bf2af",
    Address: "Darlinghurst 265 Victoria Street",
    Location: "East side, between Liverpool Street and Burton Street",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 6m long",
    StreetView: "https://goo.gl/9VWhvk",
  },
  {
    _id: "61d1752e339d0c456d8bf2b0",
    Address: "Darlinghurst St Vincent's Hospital Victoria Street",
    Location: "East side, between Burton Street and Victoria Street",
    ParkingSpace: "145-degree parking space, 3.7m wide by 8.2m long",
    Information:
      "45 degree angle parking rear to kerb. Vehicles under 6 metres only",
    StreetView: "https://goo.gl/JfXhxf",
  },
  {
    _id: "61d1752e339d0c456d8bf2b1",
    Address: "Darlinghurst 26 Womerah Avenue",
    Location: "South side, between Oswald Lane and Craigend Street",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 6.5m long",
    StreetView: "https://goo.gl/8WoLSk",
  },
  {
    _id: "61d1752e339d0c456d8bf2b2",
    Address: "Darlington 121 Darlington Road",
    Location: "South side, between Codrington Street and Golden Grove Street",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 5.4m long",
    Information: "Mobility parking 830am to 530pm Monday to Friday",
    StreetView: "https://goo.gl/KwYqxG",
  },
  {
    _id: "61d1752e339d0c456d8bf2b3",
    Address: "Darlington Darlington Road",
    Location: "South side, between Golden Grove Street and King Street",
    ParkingSpace: "2 parallel parking spaces, 3.2m wide by 6.5m long",
    StreetView: "https://goo.gl/Wjkp9o",
  },
  {
    _id: "61d1752e339d0c456d8bf2b4",
    Address: "Darlington 314 Wilson Street",
    Location: "North side, between Golden Grove Street and Codrington Street",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 6.6m long",
    StreetView: "https://goo.gl/3j4tk2",
  },
  {
    _id: "61d1752e339d0c456d8bf2b5",
    Address: "Darlington 502 Wilson Street",
    Location: "North side, between Sheppard Street and Sheppard Lane",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 6.6m long",
    StreetView: "https://goo.gl/VjqJWA",
  },
  {
    _id: "61d1752e339d0c456d8bf2b6",
    Address: "Darlington 45 Golden Grove Street",
    Location: "West side, between Wilson Street and Abercrombie Street",
    ParkingSpace: "2 parallel parking spaces, 2.4m wide by 3.6m long",
    StreetView: "https://goo.gl/4cuFJp",
  },
  {
    _id: "61d1752e339d0c456d8bf2b7",
    Address: "Darlington 54 Calder Road",
    Location: "North side, between Shephard Street and Shepard Lane",
    ParkingSpace: "1 parallel parking space, 2.2m wide by 8.6m long",
    StreetView: "https://goo.gl/XaUZfa",
  },
  {
    _id: "61d1752e339d0c456d8bf2b8",
    Address: "Darlington 129-131 Little Eveleigh Street",
    Location: "South side, between Lawson Street and Ivy Lane",
    ParkingSpace: "1 parallel parking space, 2.4m wide by 6.4m long",
    StreetView: "https://goo.gl/VrJU74",
  },
  {
    _id: "61d1752e339d0c456d8bf2b9",
    Address: "Darlington 30 Thomas Street",
    Location: "West side, between Vine Street and Ivy Lane",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 6.4m long",
    StreetView: "https://goo.gl/HTkHBq",
  },
  {
    _id: "61d1752e339d0c456d8bf2ba",
    Address: "Darlington 108-118 Shephard Street",
    Location: "East side, between Vine Street and Ivy Street",
    ParkingSpace: "2 parallel parking spaces, 2m wide by 6.2m long",
    StreetView: "https://goo.gl/TUukuT",
  },
  {
    _id: "61d1752e339d0c456d8bf2bb",
    Address: "Darlington 444 Wilson Street",
    Location: "North side, between Codrington Street and Sheppard Street",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 6.2m long",
    StreetView: "https://goo.gl/AqndD5",
  },
  {
    _id: "61d1752e339d0c456d8bf2bc",
    Address: "Darlington Darlington Public School Abercrombie Street",
    Location: "North side, between Golden Grove Street and Codrington Street",
    ParkingSpace: "2 parallel parking spaces, 3.2m wide by 6.8m long",
    Information: "Mobility parking only 8am to 6pm school days",
    StreetView: "https://goo.gl/j4EtFL",
  },
  {
    _id: "61d1752e339d0c456d8bf2bd",
    Address: "Dawes Point 36-64 George Street",
    Location: "West side, between Cahill Walk and Lower Fort Street",
    ParkingSpace: "2 parallel parking spaces, 4.4m wide by 7.2m long",
    StreetView: "https://goo.gl/gaKZea",
  },
  {
    _id: "61d1752e339d0c456d8bf2be",
    Address: "Dawes Point 5 Hickson Road",
    Location: "South side, between Napoleon Street and Pottinger Street",
    ParkingSpace: "1 parallel parking space, 2.5m wide by 6.4m long",
    StreetView: "https://goo.gl/VFbY18",
  },
  {
    _id: "61d1752e339d0c456d8bf2bf",
    Address: "Dawes Point 5 Hickson Road",
    Location: "South side, between Napoleon Street and Pottinger Street",
    ParkingSpace: "1 parallel parking space, 2.5m wide by 6.8m long",
    StreetView: "https://goo.gl/9a8MWt",
  },
  {
    _id: "61d1752e339d0c456d8bf2c0",
    Address: "Dawes Point 5 Hickson Road",
    Location: "South side, between Pottinger Street and Napoleon Street",
    ParkingSpace: "2 parallel parking spaces, 2.5m wide by 6.1m long",
    StreetView: "https://goo.gl/eKdHvy",
  },
  {
    _id: "61d1752e339d0c456d8bf2c1",
    Address: "Dawes Point 11 Hickson Road",
    Location: "East side, between Lower Fort Road and Hickson Road",
    ParkingSpace: "445-degree parking spaces, 3.2m wide by 4.9m long",
    StreetView: "https://goo.gl/Y4yQ6s",
  },
  {
    _id: "61d1752e339d0c456d8bf2c2",
    Address: "Elizabeth Bay 7 Ithaca Road",
    Location: "East side, between The Esplanade and Ithaca Road",
    ParkingSpace: "190-degree parking space, 3.7m wide by 5.1m long",
    Information:
      "90 degree angle parking rear to kerb. Vehicles under 6 metres only",
    StreetView: "https://goo.gl/JBVMB3",
  },
  {
    _id: "61d1752e339d0c456d8bf2c3",
    Address: "Elizabeth Bay 50-58 Macleay Street",
    Location: "East side, between Fitzroy Gardens and Greenknowe Avenue",
    ParkingSpace: "3 parallel parking spaces, 3.2m wide by 6m long",
    StreetView: "https://goo.gl/7vRYiY",
  },
  {
    _id: "61d1752e339d0c456d8bf2c4",
    Address: "Elizabeth Bay 39 Elizabeth Bay Road",
    Location: "East side, between Greenknowe Avenue and Amos Lane",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 5.7m long",
    StreetView: "https://goo.gl/auE8iC",
  },
  {
    _id: "61d1752e339d0c456d8bf2c5",
    Address: "Erskineville 37 Ashmore Street",
    Location: "South side, between Mitchell Road and cul de sac",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 5.4m long",
    StreetView: "https://goo.gl/3qxgSr",
  },
  {
    _id: "61d1752e339d0c456d8bf2c6",
    Address: "Erskineville Shop 14 Coulson Street",
    Location: "South side, between Mitchell Road and Eve Street",
    ParkingSpace: "160-degree parking space, 3.5m wide by 6m long",
    Information: "60 degree angle parking rear to kerb",
    StreetView: "https://goo.gl/hJC4mN",
  },
  {
    _id: "61d1752e339d0c456d8bf2c7",
    Address: "Erskineville 51 Ashmore Street",
    Location: "South side, between Mitchell Road and cul de sac",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 6.6m long",
    StreetView: "https://goo.gl/i1undt",
  },
  {
    _id: "61d1752e339d0c456d8bf2c8",
    Address: "Erskineville 24 Ashmore Street",
    Location: "South side, between Binning Street and Binning Lane",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 6.4m long",
    StreetView: "https://goo.gl/Yi1r7d",
  },
  {
    _id: "61d1752e339d0c456d8bf2c9",
    Address: "Erskineville Angel Street",
    Location: "West side, between Newman Lane and Newman Street",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 5.8m long",
    StreetView: "https://goo.gl/jLKurM",
  },
  {
    _id: "61d1752e339d0c456d8bf2ca",
    Address: "Erskineville Erskineville Mosque Charles Street",
    Location: "West side, between Erskineville Road and Albert Street",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 6.8m long",
    StreetView: "https://goo.gl/ieYiML",
  },
  {
    _id: "61d1752e339d0c456d8bf2cb",
    Address: "Erskineville 8 Flora Street",
    Location: "East side, between MacDonald Street and Coulson Street",
    ParkingSpace: "1 parallel parking space, 2.2m wide by 7.3m long",
    StreetView: "https://goo.gl/Bj8Nq1",
  },
  {
    _id: "61d1752e339d0c456d8bf2cc",
    Address: "Erskineville 201 Rochford Street",
    Location: "West side, between King Street and Knight Street",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 6m long",
    StreetView: "https://goo.gl/c5YuGC",
  },
  {
    _id: "61d1752e339d0c456d8bf2cd",
    Address: "Erskineville 29 Swanson Street",
    Location: "South side, between Elliott Avenue and Malcolm Street",
    ParkingSpace: "1 parallel parking space, 3m wide by 7.8m long",
    StreetView: "https://goo.gl/Z53uj2",
  },
  {
    _id: "61d1752e339d0c456d8bf2ce",
    Address: "Erskineville 89 Erskineville Road",
    Location: "South side, between George Street and Morrissey Road",
    ParkingSpace: "1 parallel parking space, 2.9m wide by 5.5m long",
    Information:
      "Mobility parking only, 830am to 6pm Monday to Friday and 830am to 1230pm Saturdays",
    StreetView: "https://goo.gl/ndXwhA",
  },
  {
    _id: "61d1752e339d0c456d8bf2cf",
    Address: "Erskineville Elliott Avenue",
    Location: "North side, between Binning Street and Swanson Street",
    ParkingSpace: "3 parallel parking spaces, 3.2m wide by 7m long",
    StreetView: "https://goo.gl/Cwt2wW",
  },
  {
    _id: "61d1752e339d0c456d8bf2d0",
    Address: "Erskineville 8A Amy Street",
    Location: "East side, between MacDonald Street and Knight Street",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 7m long",
    StreetView: "https://goo.gl/QUAmHJ",
  },
  {
    _id: "61d1752e339d0c456d8bf2d1",
    Address: "Eveleigh 41 Rowley Lane",
    Location: "West side, between Rowley Street and Alexander Street",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 7.2m long",
    StreetView: "https://goo.gl/2DYTXL",
  },
  {
    _id: "61d1752e339d0c456d8bf2d2",
    Address: "Forest Lodge 9-10 Arthur Street",
    Location: "East side, between Albert Street and Wigram Road",
    ParkingSpace: "2 parallel parking spaces, 3.2m wide by 7.2m long",
    StreetView: "https://goo.gl/LAkRjn",
  },
  {
    _id: "61d1752e339d0c456d8bf2d3",
    Address: "Forest Lodge 20 Forest Street",
    Location: "West side, between Arundel Street and St Johns Road",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 7.8m long",
    StreetView: "https://goo.gl/yMDSct",
  },
  {
    _id: "61d1752e339d0c456d8bf2d4",
    Address: "Forest Lodge 16 Albert Street",
    Location: "South side, between Arthur Street and Upper Road",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 6.2m long",
    StreetView: "https://goo.gl/4fZtay",
  },
  {
    _id: "61d1752e339d0c456d8bf2d5",
    Address: "Forest Lodge 3 Albert Street",
    Location: "North side, between Upper Road and Arthur Street",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 6m long",
    StreetView: "https://goo.gl/7HKG81",
  },
  {
    _id: "61d1752e339d0c456d8bf2d6",
    Address: "Glebe 94 Campbell Street",
    Location: "West side, between Norton Street and Saint Johns Road",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 5.4m long",
    StreetView: "https://goo.gl/qjWF5y",
  },
  {
    _id: "61d1752e339d0c456d8bf2d7",
    Address: "Glebe 87 Campbell Street",
    Location: "East side, between Norton Street and Mitchell Street",
    ParkingSpace: "2 parallel parking spaces, 3.2m wide by 5.9m long",
    StreetView: "https://goo.gl/pqDm8U",
  },
  {
    _id: "61d1752e339d0c456d8bf2d8",
    Address: "Glebe 31 Campbell Street",
    Location: "East side, between Mitchell Street and Cowper Street",
    ParkingSpace: "3 parallel parking spaces, 3.2m wide by 5.1m long",
    StreetView: "https://goo.gl/8sF9wF",
  },
  {
    _id: "61d1752e339d0c456d8bf2d9",
    Address: "Glebe Forsyth Street",
    Location: "South side, *parking bay east of Taylor Street near glebe for",
    ParkingSpace: "190-degree parking space, 3.2m wide by 5.4m long",
    StreetView: "https://goo.gl/ZebpTR",
  },
  {
    _id: "61d1752e339d0c456d8bf2da",
    Address: "Glebe 16 Leichhardt Street",
    Location: "South side, parking bay near Blackwattle Bay Park",
    ParkingSpace: "190-degree parking space, 3.3m wide by 5.7m long",
    StreetView: "https://goo.gl/96zdAZ",
  },
  {
    _id: "61d1752e339d0c456d8bf2db",
    Address: "Glebe Cardigan Street",
    Location: "South side, between Bellevue Lane and Wentworth Park Road",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 5.6m long",
    StreetView: "https://goo.gl/XVMd15",
  },
  {
    _id: "61d1752e339d0c456d8bf2dc",
    Address: "Glebe 21 Mitchell Street",
    Location: "North side, between Wentworth Street and Phillip Street",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 5.5m long",
    StreetView: "https://goo.gl/S9hExH",
  },
  {
    _id: "61d1752e339d0c456d8bf2dd",
    Address: "Glebe 58 Mitchell Street",
    Location: "South side, between Phillip Street and Broughton Street",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 5.8m long",
    StreetView: "https://goo.gl/GjMvkT",
  },
  {
    _id: "61d1752e339d0c456d8bf2de",
    Address: "Glebe 37 Mitchell Street",
    Location: "North side, between Phillip Street and Broughton Street",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 5.6m long",
    StreetView: "https://goo.gl/Ah1sXM",
  },
  {
    _id: "61d1752e339d0c456d8bf2df",
    Address: "Glebe 49 Mitchell Street",
    Location: "North side, between Phillip Street and Broughton Street",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 6.4m long",
    StreetView: "https://goo.gl/nz4Jdy",
  },
  {
    _id: "61d1752e339d0c456d8bf2e0",
    Address: "Glebe 11 Phillip Street",
    Location: "East side, between Mitchell Lane East and Cowper Lane",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 6.2m long",
    StreetView: "https://goo.gl/JD68b8",
  },
  {
    _id: "61d1752e339d0c456d8bf2e1",
    Address: "Glebe 43 Cowper Street",
    Location: "North side, between Wentworth Street and Phillip Street",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 6m long",
    StreetView: "https://goo.gl/JYRske",
  },
  {
    _id: "61d1752e339d0c456d8bf2e2",
    Address: "Glebe 11 Broughton Street",
    Location: "East side, between Cowper Lane and Mitchell Lane East",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 6.6m long",
    StreetView: "https://goo.gl/1LJ5R8",
  },
  {
    _id: "61d1752e339d0c456d8bf2e3",
    Address: "Glebe 1 Phillip Street",
    Location: "East side, between Mitchell Lane East and Cowper Lane",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 5.2m long",
    StreetView: "https://goo.gl/dmY2bP",
  },
  {
    _id: "61d1752e339d0c456d8bf2e4",
    Address: "Glebe 21 Broughton Street",
    Location: "East side, between Mitchell Lane West and Saint Johns Road",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 5.8m long",
    StreetView: "https://goo.gl/WNLLiU",
  },
  {
    _id: "61d1752e339d0c456d8bf2e5",
    Address: "Glebe 84 Saint Johns Road",
    Location: "South side, between Glebe Street and Bernard Lane",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 6.3m long",
    StreetView: "https://goo.gl/M1MS3s",
  },
  {
    _id: "61d1752e339d0c456d8bf2e6",
    Address: "Glebe 16 Broughton Street",
    Location: "West side, between Cowper Lane and Mitchell Street",
    ParkingSpace: "2 parallel parking spaces, 3.2m wide by 5.5m long",
    StreetView: "https://goo.gl/aWZnT2",
  },
  {
    _id: "61d1752e339d0c456d8bf2e7",
    Address: "Glebe 24 Broughton Street",
    Location: "West side, between Cowper Lane and Mitchell Street",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 6m long",
    StreetView: "https://goo.gl/f2KQWX",
  },
  {
    _id: "61d1752e339d0c456d8bf2e8",
    Address: "Glebe 75 Saint Johns Road",
    Location: "North side, between Glebe Point Road and Purves Street",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 9.2m long",
    StreetView: "https://goo.gl/9vTSEP",
  },
  {
    _id: "61d1752e339d0c456d8bf2e9",
    Address: "Glebe 128 Saint Johns Road",
    Location: "South side, between Glebe Point Road and Derwent Lane",
    ParkingSpace: "1 parallel parking space, 2m wide by 6.9m long",
    StreetView: "https://goo.gl/d6pCVX",
  },
  {
    _id: "61d1752e339d0c456d8bf2ea",
    Address: "Glebe 10 Colbourne Avenue",
    Location: "West side, between Saint Johns Road and Lyndhurst Street",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 5.9m long",
    StreetView: "https://goo.gl/2zKWYC",
  },
  {
    _id: "61d1752e339d0c456d8bf2eb",
    Address: "Glebe 62 Derwent Street",
    Location: "West side, between Mitchell Road and Saint Johns Road",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 8.3m long",
    StreetView: "https://goo.gl/KL1ddc",
  },
  {
    _id: "61d1752e339d0c456d8bf2ec",
    Address: "Glebe 451 Glebe Point Road",
    Location: "East side, between Federal Road and Mary Street",
    ParkingSpace: "1 parallel parking space, 2.2m wide by 6.8m long",
    StreetView: "https://goo.gl/q4Y1e7",
  },
  {
    _id: "61d1752e339d0c456d8bf2ed",
    Address: "Glebe 10 Bellevue Street",
    Location: "West side, between Saint Johns Road and Lyndhurst Street",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 6m long",
    StreetView: "https://goo.gl/13zVNW",
  },
  {
    _id: "61d1752e339d0c456d8bf2ee",
    Address: "Glebe 45 Westmoreland Street",
    Location: "East side, between Saint Johns Road and Mitchell Street",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 10.1m long",
    StreetView: "https://goo.gl/u8s9ib",
  },
  {
    _id: "61d1752e339d0c456d8bf2ef",
    Address: "Glebe 117 Cowper Street",
    Location: "North side, between Campbell Street and Campbell Lane",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 6m long",
    StreetView: "https://goo.gl/EUkGWC",
  },
  {
    _id: "61d1752e339d0c456d8bf2f0",
    Address: "Glebe 18 Westmoreland Street",
    Location: "West side, between Mitchell Street and Saint Johns Road",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 6m long",
    StreetView: "https://goo.gl/xh7Bnr",
  },
  {
    _id: "61d1752e339d0c456d8bf2f1",
    Address: "Glebe 96 Glebe Street",
    Location: "West side, between Cowper Street and Mitchell Street",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 6.8m long",
    StreetView: "https://goo.gl/uA8xEd",
  },
  {
    _id: "61d1752e339d0c456d8bf2f2",
    Address: "Glebe 119 Glebe Street",
    Location: "East side, between Norton Street and Mitchell Street",
    ParkingSpace: "2 parallel parking spaces, 3.2m wide by 6.2m long",
    StreetView: "https://goo.gl/AFy7BR",
  },
  {
    _id: "61d1752e339d0c456d8bf2f3",
    Address: "Glebe 65 Arundel Street",
    Location: "South side, between Derwent Street and Seamer Street",
    ParkingSpace: "190-degree parking space, 4.8m wide by 4.9m long",
    StreetView: "https://goo.gl/tiknsZ",
  },
  {
    _id: "61d1752e339d0c456d8bf2f4",
    Address: "Glebe 45 Arundel Street",
    Location: "North side, between Derwent Street and Seamer Street",
    ParkingSpace: "1 parallel parking space, 2.2m wide by 6.5m long",
    StreetView: "https://goo.gl/Zx1W2d",
  },
  {
    _id: "61d1752e339d0c456d8bf2f5",
    Address: "Glebe Catherine Street",
    Location: "North side, between Mount Vernon Street and Mount Vernon Lane",
    ParkingSpace: "1 parallel parking space, 3.5m wide by 10.1m long",
    StreetView: "https://goo.gl/7ikZZi",
  },
  {
    _id: "61d1752e339d0c456d8bf2f6",
    Address: "Glebe 3 Westmoreland Street",
    Location: "East side, between Mitchell Street and Catherine Street",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 4.7m long",
    StreetView: "https://goo.gl/qsmjjg",
  },
  {
    _id: "61d1752e339d0c456d8bf2f7",
    Address: "Glebe 48 Saint Johns Road",
    Location: "South side, between Phillip Street and Wentworth Street",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 5.4m long",
    StreetView: "https://goo.gl/cmvCaJ",
  },
  {
    _id: "61d1752e339d0c456d8bf2f8",
    Address: "Glebe 76 Forsyth Street",
    Location: "South side, between Taylor Street and Avon Street",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 6.4m long",
    StreetView: "https://goo.gl/fE2Q4P",
  },
  {
    _id: "61d1752e339d0c456d8bf2f9",
    Address: "Glebe 42 Allen Street",
    Location: "East side, between Cotter Lane and Park Avenue",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 7.8m long",
    StreetView: "https://goo.gl/GwJNfA",
  },
  {
    _id: "61d1752e339d0c456d8bf2fa",
    Address: "Glebe 63 Westmoreland Street",
    Location: "East side, between Saint Johns Road and Mitchell Street",
    ParkingSpace: "2 parallel parking spaces, 3.2m wide by 6m long",
    StreetView: "https://goo.gl/Abqgtw",
  },
  {
    _id: "61d1752e339d0c456d8bf2fb",
    Address: "Glebe 315 Glebe Point Road",
    Location: "East side, between Ferry Road and Palmerston Avenue",
    ParkingSpace: "1 parallel parking space, 2.2m wide by 6.1m long",
    StreetView: "https://goo.gl/gp4QDD",
  },
  {
    _id: "61d1752e339d0c456d8bf2fc",
    Address: "Glebe 79 Westmoreland Street",
    Location: "East side, between Saint Johns Road and Mitchell Street",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 7.2m long",
    StreetView: "https://goo.gl/xusV3n",
  },
  {
    _id: "61d1752e339d0c456d8bf2fd",
    Address: "Glebe 39 Bellevue Street",
    Location: "East side, between Lyndhurst Street and Saint Johns Road",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 7m long",
    StreetView: "https://goo.gl/6L5Mmc",
  },
  {
    _id: "61d1752e339d0c456d8bf2fe",
    Address: "Glebe 103 Glebe Street",
    Location: "East side, between Cowper Street and Mitchell Street",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 6m long",
    StreetView: "https://goo.gl/49hFMs",
  },
  {
    _id: "61d1752e339d0c456d8bf2ff",
    Address: "Glebe 20 Derwent Street",
    Location: "West side, between Catherine Street and Mitchell Street",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 8.6m long",
    StreetView: "https://goo.gl/nJtjxa",
  },
  {
    _id: "61d1752e339d0c456d8bf300",
    Address: "Glebe 93 Arundel Street",
    Location: "North side, between Forest Street and Lodge Street",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 5.2m long",
    StreetView: "https://goo.gl/HBewQW",
  },
  {
    _id: "61d1752e339d0c456d8bf301",
    Address: "Glebe 71-73 Derwent Street",
    Location: "East side, between Saint Johns Road and Mitchell Street",
    ParkingSpace: "3 parallel parking spaces, 3.2m wide by 8.2m long",
    StreetView: "https://goo.gl/DRCW6G",
  },
  {
    _id: "61d1752e339d0c456d8bf302",
    Address: "Glebe 21 Mount Vernon Street",
    Location: "East side, between Saint Johns Road and Catherine Street",
    ParkingSpace: "3 parallel parking spaces, 3.2m wide by 6.4m long",
    StreetView: "https://goo.gl/iSdT63",
  },
  {
    _id: "61d1752e339d0c456d8bf303",
    Address: "Haymarket 13 Campbell Street",
    Location: "South side, between Pitt Street and George Street",
    ParkingSpace: "2 parallel parking spaces, 3.2m wide by 6.4m long",
    StreetView: "https://goo.gl/8UBdBw",
  },
  {
    _id: "61d1752e339d0c456d8bf304",
    Address: "Haymarket 11 Rawson Place",
    Location: "North side, between George Street and Pitt Street",
    ParkingSpace: "2 parallel parking spaces, 2.8m wide by 5.5m long",
    StreetView: "https://goo.gl/maps/s9yCBUyXEyp3dAGbA",
  },
  {
    _id: "61d1752e339d0c456d8bf305",
    Address: "Haymarket McKell Building Barlow Street",
    Location: "South side, between Barlow Street and George Street",
    ParkingSpace: "2 parallel parking spaces, 3.2m wide by 5.4m long",
    StreetView: "https://goo.gl/U9wPy6",
  },
  {
    _id: "61d1752e339d0c456d8bf306",
    Address: "Haymarket 2 Quay Street",
    Location: "West side, between Ultimo Road and Hay Street",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 7.1m long",
    StreetView: "https://goo.gl/e7bab6",
  },
  {
    _id: "61d1752e339d0c456d8bf307",
    Address: "Haymarket 405-411 Sussex Street",
    Location: "East side, between Hay Street to Little Hay Street",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 5.7m long",
    StreetView: "https://goo.gl/4a9Csf",
  },
  {
    _id: "61d1752e339d0c456d8bf308",
    Address:
      "Haymarket Central Station Western Forecourt Railway Colonnade Drive",
    Location: "East side, between Lee Street an Eddy Avenue",
    ParkingSpace: "290-degree parking spaces, 2.5m wide by 5.4m long",
    Information: "Managed by RailCorp",
    StreetView: "https://goo.gl/zpP2y7",
  },
  {
    _id: "61d1752e339d0c456d8bf309",
    Address: "Haymarket 10 Quay Street",
    Location: "East side, between Bijou Lane and Thomas Street",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 5.8m long",
    StreetView: "https://goo.gl/SVewpR",
  },
  {
    _id: "61d1752e339d0c456d8bf30a",
    Address: "Millers Point 84 Kent Street",
    Location: "East side, between Argyle Street and High Street",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 6.3m long",
    StreetView: "https://goo.gl/J95Hjx",
  },
  {
    _id: "61d1752e339d0c456d8bf30b",
    Address: "Millers Point 6 Towns Place",
    Location: "N/A, between Dalgety Road and Hickson Road",
    ParkingSpace: "290-degree parking spaces, 2.5m wide by 4.8m long",
    Information:
      "90 degree angle parking rear to kerb. Vehicles under 6 metres only",
    StreetView: "https://goo.gl/maps/ra9o9hMAuExWH7hq7",
  },
  {
    _id: "61d1752e339d0c456d8bf30c",
    Address: "Millers Point Nawi Square Lawn Hickson Road",
    Location: "West side, between Towns Place and Napoleon Street",
    ParkingSpace: "290-degree parking spaces, 3.6m wide by 5.2m long",
    StreetView: "https://goo.gl/7p29Jh",
  },
  {
    _id: "61d1752e339d0c456d8bf30d",
    Address: "Newtown 16 Brown Street",
    Location: "East side, between Buckland Lane and Bruce Lane",
    ParkingSpace: "1 parallel parking space, 2.3m wide by 4.8m long",
    StreetView: "https://goo.gl/KDXzVs",
  },
  {
    _id: "61d1752e339d0c456d8bf30e",
    Address: "Newtown Watkin Street",
    Location: "West side, between Buckland Lane and King Street",
    ParkingSpace: "2 parallel parking spaces, 3.2m wide by 6.3m long",
    StreetView: "https://goo.gl/oD7rkC",
  },
  {
    _id: "61d1752e339d0c456d8bf30f",
    Address: "Newtown 25 Brown Street",
    Location: "West side, between Linthorpe Street and Linthorpe Lane",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 6.4m long",
    StreetView: "https://goo.gl/maps/ySHcUczpZA942pHx6",
  },
  {
    _id: "61d1752e339d0c456d8bf310",
    Address: "Newtown 22-28 Wilson Street",
    Location: "South side, between Erskineville Road and Brown Street",
    ParkingSpace: "290-degree parking spaces, 2.6m wide by 5.3m long",
    StreetView: "https://goo.gl/SrSsRW",
  },
  {
    _id: "61d1752e339d0c456d8bf311",
    Address: "Newtown Stephen Street",
    Location: "East side, between Longdown Street and Victoria Street",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 7m long",
    StreetView: "https://goo.gl/4J3E9h",
  },
  {
    _id: "61d1752e339d0c456d8bf312",
    Address: "Newtown Newtown Library Brown Street",
    Location: "East side, between Buckland Lane and Brown Lane",
    ParkingSpace: "1 parallel parking space, 2.3m wide by 5.8m long",
    StreetView: "https://goo.gl/eC5hPc",
  },
  {
    _id: "61d1752e339d0c456d8bf313",
    Address: "Newtown 69 Campbell Street",
    Location: "North side, between Missenden Road and Little Queen Street",
    ParkingSpace: "2 parallel parking spaces, 3.2m wide by 6.3m long",
    StreetView: "https://goo.gl/XdDaua",
  },
  {
    _id: "61d1752e339d0c456d8bf314",
    Address: "Newtown 50 O'Connell Street",
    Location: "West side, between Chalder Street and Prospect Street",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 5.4m long",
    StreetView: "https://goo.gl/vgVP1R",
  },
  {
    _id: "61d1752e339d0c456d8bf315",
    Address: "Newtown 56 Forbes Street",
    Location: "East side, between Elvy Place and Wilson Street",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 6.2m long",
    StreetView: "https://goo.gl/3ASDoa",
  },
  {
    _id: "61d1752e339d0c456d8bf316",
    Address: "Newtown 67 O'Connell Street",
    Location: "East side, between Carillon Street and Campbell Street",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 7.6m long",
    StreetView: "https://goo.gl/4AGV7b",
  },
  {
    _id: "61d1752e339d0c456d8bf317",
    Address: "Paddington 16 Albion Avenue",
    Location: "North side, between South Dowling Street and Selwyn Street",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 7m long",
    StreetView: "https://goo.gl/365Shu",
  },
  {
    _id: "61d1752e339d0c456d8bf318",
    Address: "Paddington 26 Josephson Street",
    Location: "South side, between Greens Road and Selwyn Street",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 6.7m long",
    StreetView: "https://goo.gl/2YAvEY",
  },
  {
    _id: "61d1752e339d0c456d8bf319",
    Address: "Paddington 1 Oatley Road",
    Location: "West side, between Renny Street and Oatley Road",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 5.6m long",
    StreetView: "https://goo.gl/2jPTsV",
  },
  {
    _id: "61d1752e339d0c456d8bf31a",
    Address: "Potts Point 81 Macleay Street",
    Location: "West side, between Manning Street and Rockwall Crescent",
    ParkingSpace: "2 parallel parking spaces, 3.2m wide by 5.7m long",
    StreetView: "https://goo.gl/RXagid",
  },
  {
    _id: "61d1752e339d0c456d8bf31b",
    Address: "Pyrmont Pirrama Park Pirrama Road",
    Location: "West side, between Harris Street and Jones Bay Road",
    ParkingSpace: "290-degree parking spaces, 3.2m wide by 5.4m long",
    Information:
      "90 degree angle parking rear to kerb. Vehicles under 6 metres only",
    StreetView: "https://goo.gl/6Heazt",
  },
  {
    _id: "61d1752e339d0c456d8bf31c",
    Address: "Pyrmont 18 Point Street",
    Location: "East side, between Scott Street and Bowman Street",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 7m long",
    StreetView: "https://goo.gl/MmAbGw",
  },
  {
    _id: "61d1752e339d0c456d8bf31d",
    Address: "Pyrmont 9 Harris Street",
    Location: "East side, between Pirrama Road and Pirrama Park",
    ParkingSpace: "2 parallel parking spaces, 3.2m wide by 7.6m long",
    StreetView: "https://goo.gl/K6QydD",
  },
  {
    _id: "61d1752e339d0c456d8bf31e",
    Address: "Pyrmont Pirrama Park Pirrama Road",
    Location: "North side, between Herbert Street and Jones Bay Wharf",
    ParkingSpace: "290-degree parking spaces, 3.2m wide by 5.4m long",
    Information:
      "90 degree angle parking rear to kerb. Vehicles under 6 metres only",
    StreetView: "https://goo.gl/4nmGs4",
  },
  {
    _id: "61d1752e339d0c456d8bf31f",
    Address: "Pyrmont 21-27 Jones Street",
    Location: "West side, between Miller Street and Clifftop Walk",
    ParkingSpace: "190-degree parking space, 3.5m wide by 5m long",
    Information: "90 degree angle parking front to kerb",
    StreetView: "https://goo.gl/m7QXpm",
  },
  {
    _id: "61d1752e339d0c456d8bf320",
    Address: "Redfern 103-109 George Street",
    Location: "East side, between Redfern Street and Turner Street",
    ParkingSpace: "1 parallel parking space, 2.3m wide by 5.8m long",
    StreetView: "https://goo.gl/AtKizC",
  },
  {
    _id: "61d1752e339d0c456d8bf321",
    Address: "Redfern Boundary Street",
    Location: "South side, between Wyndham Street and Regent Street",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 7.8m long",
    StreetView: "https://goo.gl/bPNUFx",
  },
  {
    _id: "61d1752e339d0c456d8bf322",
    Address: "Redfern 107 Redfern Street",
    Location: "South side, between Pitt Street and George Street",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 5.4m long",
    StreetView: "https://goo.gl/WY8zs8",
  },
  {
    _id: "61d1752e339d0c456d8bf323",
    Address: "Redfern 76 George Street",
    Location: "West side, between Wells Street and James Street",
    ParkingSpace: "1 parallel parking space, 2.4m wide by 5.5m long",
    StreetView: "https://goo.gl/NvyXdQ",
  },
  {
    _id: "61d1752e339d0c456d8bf324",
    Address: "Redfern 261 Chalmers Street",
    Location: "East side, between Turner Street and Phillip Street",
    ParkingSpace: "160-degree parking space, 3.4m wide by 5.6m long",
    Information: "Rear to kerb parking",
    StreetView: "https://goo.gl/FCHFUf",
  },
  {
    _id: "61d1752e339d0c456d8bf325",
    Address: "Redfern 10 Pitt Street",
    Location: "West side, between Wells Street and James Street",
    ParkingSpace: "160-degree parking space, 3.2m wide by 5.4m long",
    StreetView: "https://goo.gl/7JWDNT",
  },
  {
    _id: "61d1752e339d0c456d8bf326",
    Address: "Redfern 13 Garden Street",
    Location: "West side, between Central Avenue and Locomotive Street",
    ParkingSpace: "390-degree parking spaces, 4m wide by 5.4m long",
    StreetView: "https://goo.gl/DcHyMJ",
  },
  {
    _id: "61d1752e339d0c456d8bf327",
    Address: "Redfern 6 Zamia Street",
    Location: "South side, between Baptist Street and Baptist Lane",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 5.2m long",
    StreetView: "https://goo.gl/ZGeQzo",
  },
  {
    _id: "61d1752e339d0c456d8bf328",
    Address: "Redfern 16 Cope Street",
    Location: "West side, between Phillip Street and Turner Street",
    ParkingSpace: "3 parallel parking spaces, 3.2m wide by 5.6m long",
    Information: "Mobility parking only, 7am to 5pm Monday to Friday",
    StreetView: "https://goo.gl/Xke29G",
  },
  {
    _id: "61d1752e339d0c456d8bf329",
    Address: "Redfern 267 Chalmers Street",
    Location: "East side, between Turner Street and Phillip Street",
    ParkingSpace: "160-degree parking space, 3.9m wide by 6m long",
    Information: "Rear to kerb parking",
    StreetView: "https://goo.gl/XQCiHA",
  },
  {
    _id: "61d1752e339d0c456d8bf32a",
    Address: "Redfern Redfern Police Station Lawson Square",
    Location: "South side, between Regent Street and Gibbons Street",
    ParkingSpace: "160-degree parking space, 3m wide by 5.9m long",
    Information: "Police vehicles excepted",
    StreetView: "https://goo.gl/PXz678",
  },
  {
    _id: "61d1752e339d0c456d8bf32b",
    Address: "Redfern 19 Thurlow Street",
    Location: "South side, between Thurlow Lane and Bourke Street",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 7m long",
    StreetView: "https://goo.gl/RZPb4J",
  },
  {
    _id: "61d1752e339d0c456d8bf32c",
    Address: "Rushcutters Bay 31 Roslyn Street",
    Location: "East side, between Ward Avenue and Roslyn Gardens",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 7.3m long",
    StreetView: "https://goo.gl/G6D51Y",
  },
  {
    _id: "61d1752e339d0c456d8bf32d",
    Address: "St Peters Sydney Park Harber Street",
    Location: "East side, parking bay in Sydney Park",
    ParkingSpace: "290-degree parking spaces, 3.2m wide by 5.4m long",
    Information: "90 degree angle parking rear to kerb",
    StreetView: "https://goo.gl/maps/hVXN3Xo4aXc5efh36",
  },
  {
    _id: "61d1752e339d0c456d8bf32e",
    Address: "Surry Hills 11 Ann Street",
    Location: "North side, between Batman Lane and Smith Street",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 5.4m long",
    StreetView: "https://goo.gl/aipcnm",
  },
  {
    _id: "61d1752e339d0c456d8bf32f",
    Address: "Surry Hills 120 Chalmers Street",
    Location: "West side, between Chalmers Lane and Rutland Street",
    ParkingSpace: "2 parallel parking spaces, 3.2m wide by 7m long",
    Information:
      "Mobility parking only, 10am to 3pm Monday to Friday and 6am to 8pm Saturday to Sunday",
    StreetView: "https://goo.gl/Bt2qxq",
  },
  {
    _id: "61d1752e339d0c456d8bf330",
    Address: "Surry Hills 33 Phelps Street",
    Location: "North side, between Kendall Street and Phelps Lane",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 5.8m long",
    StreetView: "https://goo.gl/J2B5ng",
  },
  {
    _id: "61d1752e339d0c456d8bf331",
    Address: "Surry Hills 63-73 Ann Street",
    Location: "South side, between Riley Street and Lt Riley Street",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 6.4m long",
    StreetView: "https://goo.gl/ebEHya",
  },
  {
    _id: "61d1752e339d0c456d8bf332",
    Address: "Surry Hills Central Station Chalmers Street",
    Location: "East side, between Randle Street and Elizabeth Street",
    ParkingSpace: "3 parallel parking spaces, 3.2m wide by 6m long",
    StreetView: "https://goo.gl/jgwWMr",
  },
  {
    _id: "61d1752e339d0c456d8bf333",
    Address: "Surry Hills 25 Pelican Street",
    Location: "West side, between Goulburn Street and Poplar Street",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 6.6m long",
    StreetView: "https://goo.gl/vyvrtQ",
  },
  {
    _id: "61d1752e339d0c456d8bf334",
    Address: "Surry Hills 3 Little Norton Street",
    Location: "West side, between Foveaux Street and Fitzroy Street",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 8.8m long",
    StreetView: "https://goo.gl/mVYAdM",
  },
  {
    _id: "61d1752e339d0c456d8bf335",
    Address: "Surry Hills 624 Crown Street",
    Location: "East side, between Lansdowne Street and Cleveland Street",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 7.5m long",
    StreetView: "https://goo.gl/1zr3xa",
  },
  {
    _id: "61d1752e339d0c456d8bf336",
    Address: "Surry Hills 16 Chapman Street",
    Location: "East side, between Phelps Street and Prospect Street",
    ParkingSpace: "190-degree parking space, 2.5m wide by 5m long",
    Information: "Vehicles under 6 metres only",
    StreetView: "https://goo.gl/HFRS5q",
  },
  {
    _id: "61d1752e339d0c456d8bf337",
    Address: "Surry Hills 468 Bourke Street",
    Location: "West side, between Prospect Street and Phelps Street",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 6.2m long",
    StreetView: "https://goo.gl/p2QCfk",
  },
  {
    _id: "61d1752e339d0c456d8bf338",
    Address: "Surry Hills Arthur Street",
    Location: "South side, between Crown Street and Tudor Place",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 7m long",
    StreetView: "https://goo.gl/y7sMq1",
  },
  {
    _id: "61d1752e339d0c456d8bf339",
    Address: "Sydney 252 Pitt Street",
    Location: "West side, between Druitt Street and Market Street",
    ParkingSpace: "2 parallel parking spaces, 2.6m wide by 8.7m long",
    Information:
      "Loading zone from 6am to 6pm Monday to Friday and 6am to 10am Saturdays",
    StreetView: "https://goo.gl/TRPpgv",
  },
  {
    _id: "61d1752e339d0c456d8bf33a",
    Address: "Sydney Saint Mary's Cathedral College Street",
    Location: "East side, between Cathedral Square and Saint Marys Road",
    ParkingSpace: "2 parallel parking spaces, 2.8m wide by 5.3m long",
    StreetView: "https://goo.gl/kvqBWx",
  },
  {
    _id: "61d1752e339d0c456d8bf33b",
    Address: "Sydney 142 Clarence Street",
    Location: "East side, between Market Street and King Street",
    ParkingSpace: "2 parallel parking spaces, 3.2m wide by 5.1m long",
    StreetView: "https://goo.gl/yZvYrB",
  },
  {
    _id: "61d1752e339d0c456d8bf33c",
    Address: "Sydney 338 Pitt Street",
    Location: "East side, between Liverpool Street and Central Street",
    ParkingSpace: "1 parallel parking space, 2.4m wide by 6m long",
    Information: "Loading zone from 6am to 10am, Monday to Friday",
    StreetView: "https://goo.gl/Jmd5z6",
  },
  {
    _id: "61d1752e339d0c456d8bf33d",
    Address: "Sydney Christian Brothers College Cathedral Street",
    Location: "North side, between Cathedral Square and Saint Marys Road",
    ParkingSpace: "1 parallel parking space, 2.8m wide by 6.8m long",
    Information: "4 hour parking, 8am to 6pm",
    StreetView: "https://goo.gl/ojBZL7",
  },
  {
    _id: "61d1752e339d0c456d8bf33e",
    Address: "Sydney 32 Grosvenor Street",
    Location: "North side, between Harrington Street and George Street",
    ParkingSpace: "1 parallel parking space, 2.5m wide by 7.8m long",
    StreetView: "https://goo.gl/oUgcFA",
  },
  {
    _id: "61d1752e339d0c456d8bf33f",
    Address: "Sydney 28 Clarence Street",
    Location: "East side, between Margaret Street and Jamison Street",
    ParkingSpace: "2 parallel parking spaces, 2.6m wide by 6.1m long",
    StreetView: "https://goo.gl/8B2udp",
  },
  {
    _id: "61d1752e339d0c456d8bf340",
    Address: "Sydney 155 Macquarie Street",
    Location: "West side, between Bent Street and Bridge Street",
    ParkingSpace: "2 parallel parking spaces, 2.8m wide by 7m long",
    StreetView: "https://goo.gl/4NxDEr",
  },
  {
    _id: "61d1752e339d0c456d8bf341",
    Address: "Sydney 2-6 Barrack Street",
    Location: "North side, between York Lane and Clarence Street",
    ParkingSpace: "2 parallel parking spaces, 2.6m wide by 6.6m long",
    Information:
      "Loading zone from 6am to 10pm, Monday to Saturday. Mobility parking other times",
    StreetView: "https://goo.gl/chvsyk",
  },
  {
    _id: "61d1752e339d0c456d8bf342",
    Address: "Sydney 7 Wheat Road",
    Location: "West side, between Harbour Street and Pyrmont Bridge",
    ParkingSpace: "590-degree parking spaces, 3.5m wide by 5.4m long",
    StreetView: "https://goo.gl/qiX4mn",
  },
  {
    _id: "61d1752e339d0c456d8bf343",
    Address: "Sydney Supreme Court of NSW Saint James Road",
    Location: "South side, between Macquarie Street and Elizabeth Street",
    ParkingSpace: "6 parallel parking spaces, 3.2m wide by 5.6m long",
    StreetView: "https://goo.gl/sDUU7M",
  },
  {
    _id: "61d1752e339d0c456d8bf344",
    Address: "Sydney 45-54 Pitt Street",
    Location: "East side, corner of Pitt Street and Bridge Street",
    ParkingSpace: "1 parallel parking space, m wide by m long",
    Information: "Mobility parking only. 2 hour ticketed parking. 6am to 6pm",
    StreetView: "https://goo.gl/maps/NS22U23YZWJeAPRM9",
  },
  {
    _id: "61d1752e339d0c456d8bf345",
    Address: "Sydney 68 Pitt Street",
    Location: "East side, corner of Pitt Street and Hunt Street",
    ParkingSpace: "1 parallel parking space, m wide by m long",
    Information: "Mobility parking only. 2 hour ticketed parking. 6am to 6pm",
    StreetView: "https://goo.gl/maps/G6UKLEEnSge1sCLp7",
  },
  {
    _id: "61d1752e339d0c456d8bf346",
    Address: "Sydney Art Gallery of NSW Art Gallery Road",
    Location: "East side, *between Sir John Young Cresc and Prince Albert Rd",
    ParkingSpace: "290-degree parking spaces, 2.7m wide by 5.2m long",
    StreetView: "https://goo.gl/2DtPjC",
  },
  {
    _id: "61d1752e339d0c456d8bf347",
    Address: "Sydney 227 Macquarie Street",
    Location: "West side, between Saint James Road and Martin Place",
    ParkingSpace: "2 parallel parking spaces, 2.9m wide by 6.9m long",
    StreetView: "https://goo.gl/AF774s",
  },
  {
    _id: "61d1752e339d0c456d8bf348",
    Address: "Sydney 180 Phillip Street",
    Location: "East side, between Martin Place and King Street",
    ParkingSpace: "2 parallel parking spaces, 3.2m wide by 6.9m long",
    Information: "4 hour ticketed parking. 8am to 6pm Monday to Friday",
    StreetView: "https://goo.gl/pThXao",
  },
  {
    _id: "61d1752e339d0c456d8bf349",
    Address: "Sydney State Library of NSW Shakespeare Place",
    Location: "South side, *between Sir John Young Crescent and Macquarie St",
    ParkingSpace: "4 parallel parking spaces, 3.2m wide by 5.9m long",
    StreetView: "https://goo.gl/QCZzdD",
  },
  {
    _id: "61d1752e339d0c456d8bf34a",
    Address: "Sydney 1 Jamison Street",
    Location: "North side, between Clarence Street and York Street",
    ParkingSpace: "2 parallel parking spaces, 3.2m wide by 5.6m long",
    StreetView: "https://goo.gl/7n9rj1",
  },
  {
    _id: "61d1752e339d0c456d8bf34b",
    Address: "Sydney Barrack Street",
    Location: "North side, between York Street and York Lane",
    ParkingSpace: "2 parallel parking spaces, 2.6m wide by 7.4m long",
    Information:
      "Loading zone from 6am to 10pm, Monday to Saturday. Mobility parking other times",
    StreetView: "https://goo.gl/LVnFmK",
  },
  {
    _id: "61d1752e339d0c456d8bf34c",
    Address: "The Rocks 107 George Street",
    Location: "West side, between Globe Street and Argyle Street",
    ParkingSpace: "3 parallel parking spaces, 3.3m wide by 6.2m long",
    Information: "15 minute drop off only 9am to 6pm",
    StreetView: "https://goo.gl/X1eEXa",
  },
  {
    _id: "61d1752e339d0c456d8bf34d",
    Address: "The Rocks 121-127 Harrington Street",
    Location: "East side, between Essex Street and Grosvenor Street",
    ParkingSpace: "3 parallel parking spaces, 3.2m wide by 6.7m long",
    StreetView: "https://goo.gl/tqS7An",
  },
  {
    _id: "61d1752e339d0c456d8bf34e",
    Address: "The Rocks King George Fifth Recreation Centre Cumberland Street",
    Location: "West side, between Cahill Walk and Gloucester Street",
    ParkingSpace: "1 parallel parking space, 2.5m wide by 9.4m long",
    StreetView: "https://goo.gl/4xPAMm",
  },
  {
    _id: "61d1752e339d0c456d8bf34f",
    Address: "Ultimo 71 Macarthur Street",
    Location: "South side, between Hackett Street and Bulwara Road",
    ParkingSpace: "190-degree parking space, 3.4m wide by 5.4m long",
    Information:
      "90 degree angle parking front to kerb. Vehicles under 6 metres only",
    StreetView: "https://goo.gl/bgK47y",
  },
  {
    _id: "61d1752e339d0c456d8bf350",
    Address: "Ultimo Ultimo TAFE Mary Ann Street",
    Location: "South side, between Jones Street and Harris Street",
    ParkingSpace: "2 parallel parking spaces, 2.2m wide by 5.4m long",
    StreetView: "https://goo.gl/bQvmXe",
  },
  {
    _id: "61d1752e339d0c456d8bf351",
    Address: "Ultimo 292 Jones Lane",
    Location: "East side, between Fig Street",
    ParkingSpace: "190-degree parking space, 3.2m wide by 5m long",
    StreetView: "https://goo.gl/9SJ1uM",
  },
  {
    _id: "61d1752e339d0c456d8bf352",
    Address: "Ultimo Bulwara Road",
    Location: "East side, between Macarthur Street and Mary Ann Street",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 7.9m long",
    StreetView: "https://goo.gl/C37U71",
  },
  {
    _id: "61d1752e339d0c456d8bf353",
    Address: "Ultimo 80 Upper Fig Street",
    Location: "South side, between Bulwara Road and Jones Street",
    ParkingSpace: "2 parallel parking spaces, 3.2m wide by 6.2m long",
    StreetView: "https://goo.gl/81L6iq",
  },
  {
    _id: "61d1752e339d0c456d8bf354",
    Address: "Ultimo 352 Jones Street",
    Location: "East side, between Fig Lane and Quarry Lane",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 6.1m long",
    StreetView: "https://goo.gl/ceQ7xf",
  },
  {
    _id: "61d1752e339d0c456d8bf355",
    Address: "Ultimo 23 Mountain Street",
    Location: "East side, between Kelly Street and Small Street",
    ParkingSpace: "2 parallel parking spaces, 3.2m wide by 5.6m long",
    StreetView: "https://goo.gl/z41YLJ",
  },
  {
    _id: "61d1752e339d0c456d8bf356",
    Address: "Waterloo 22-26 McEvoy Street",
    Location: "South side, between Hunter Street and Elizabeth Street",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 6.3m long",
    StreetView: "https://goo.gl/P3QJSM",
  },
  {
    _id: "61d1752e339d0c456d8bf357",
    Address: "Waterloo 251 Cope Street",
    Location: "East side, between John Street and McEvoy Street",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 7.8m long",
    StreetView: "https://goo.gl/cjbefq",
  },
  {
    _id: "61d1752e339d0c456d8bf358",
    Address: "Waterloo 22-26 McEvoy Street",
    Location: "South side, between Hunter Street and Elizabeth Street",
    ParkingSpace: "3 parallel parking spaces, 3.2m wide by 7.8m long",
    Information: "No parking 4pm to 6pm Monday to Friday",
    StreetView: "https://goo.gl/HU5gWL",
  },
  {
    _id: "61d1752e339d0c456d8bf359",
    Address: "Waterloo Lenton Parade",
    Location: "South side, between Raglan Lane and Wellington Street",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 7.5m long",
    StreetView: "https://goo.gl/LqpVE5",
  },
  {
    _id: "61d1752e339d0c456d8bf35a",
    Address: "Waterloo 43 Wellington Street",
    Location: "North side, between Park Lane and Wellington Lane",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 5.4m long",
    StreetView: "https://goo.gl/z6g5TD",
  },
  {
    _id: "61d1752e339d0c456d8bf35b",
    Address: "Woolloomooloo 18 Crown Street",
    Location: "East side, *between Sir John Young Crescent and Cathedral Str",
    ParkingSpace: "1 parallel parking space, 2.2m wide by 8.4m long",
    StreetView: "https://goo.gl/d4cHLQ",
  },
  {
    _id: "61d1752e339d0c456d8bf35c",
    Address: "Woolloomooloo 13 Nicholson Street",
    Location: "South side, between Maclean Street and Forbes Street",
    ParkingSpace: "2 parallel parking spaces, 3.2m wide by 7.5m long",
    StreetView: "https://goo.gl/QeY8hJ",
  },
  {
    _id: "61d1752e339d0c456d8bf35d",
    Address: "Woolloomooloo 153 Dowling Street",
    Location: "West side, between William Street and Reid Avenue",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 5.1m long",
    StreetView: "https://goo.gl/4id59s",
  },
  {
    _id: "61d1752e339d0c456d8bf35e",
    Address: "Woolloomooloo 52 McElhone Street",
    Location: "East side, between Nesbitt Street and Pring Street",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 6m long",
    StreetView: "https://goo.gl/SckAE1",
  },
  {
    _id: "61d1752e339d0c456d8bf35f",
    Address: "Woolloomooloo 128 McElhone Street",
    Location: "East side, between Windeyer Street and Rae Place",
    ParkingSpace: "2 parallel parking spaces, 3.2m wide by 5.8m long",
    StreetView: "https://goo.gl/QByd9G",
  },
  {
    _id: "61d1752e339d0c456d8bf360",
    Address: "Zetland 17 Hansard Street",
    Location: "South side, between Emmanuel Lane and Dunning Avenue",
    ParkingSpace: "160-degree parking space, 3.4m wide by 5.8m long",
    StreetView: "https://goo.gl/Mx9HBZ",
  },
  {
    _id: "61d1752e339d0c456d8bf361",
    Address: "Zetland 65 Portman Street",
    Location: "West side, between Hansard Street and Merton Street",
    ParkingSpace: "1 parallel parking space, 3.2m wide by 6m long",
    StreetView: "https://goo.gl/TP9iue",
  },
];

const Item = ({ title, info, moreinfo }) => (
  <View style={styles.item}>
    <Text style={styles.title}>{title}</Text>
    <Text style={styles.parkingSpace}>Location : {info}</Text>
    <Text style={styles.parkingSpace}>More Info : {moreinfo}</Text>
  </View>
);

const App = () => {
  //for search functionality
  const [text, setText] = useState("");
  const [data, setData] = useState();

  useEffect(() => {
    setData(DATA);
  }, []);

  //filtering data by search
  const filteredData = text
    ? data.filter((item) => {
        const itemData = item.Address.toUpperCase();
        const textData = text.toUpperCase();
        return itemData.indexOf(textData) > -1;
      })
    : data;

  //render parking carview
  const renderItem = ({ item, key }) => {
    return (
      <Item
        title={item.Address}
        info={item.ParkingSpace}
        moreinfo={item.Location}
      />
    );
  };

  //render container
  return (
    <SafeAreaView style={styles.container}>
      <TextInput
        style={styles.textInput}
        onChangeText={(text) => setText(text)}
        value={text}
        underlineColorAndroid="trasparent"
        placeholder="Search Here"
      />
      <FlatList
        data={filteredData}
        renderItem={renderItem}
        keyExtractor={(item) => item.id}
      />
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    marginTop: StatusBar.currentHeight || 0,
  },
  item: {
    backgroundColor: "#002664",
    padding: 20,
    marginVertical: 8,
    marginHorizontal: 16,
  },
  title: {
    color: "white",
    fontSize: 20,
  },
  parkingSpace: {
    fontSize: 15,
    color: "#CBEDFD",
  },
  textInput: {
    borderWidth: 1,
    borderColor: "black",
    padding: 10,
    margin: 10,
    borderRadius: 20,
  },
});

export default App;
